// Generated by `wrangler types` — re-run after changing wrangler.jsonc bindings.
interface __BaseEnv_Env {
  OUTER_DO: DurableObjectNamespace<import("./src/worker").OuterDO>;
  OUTER_FILES: R2Bucket;
  // secret — set via `wrangler secret put AUTH_SECRET` (undefined in local dev without .dev.vars)
  AUTH_SECRET?: string;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/worker");
    durableNamespaces: "OuterDO";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
