// Generated by `wrangler types` — re-run after changing wrangler.jsonc bindings.
interface __BaseEnv_Env {
  OUTER_DO: DurableObjectNamespace<import("./src/worker").OuterDO>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/worker");
    durableNamespaces: "OuterDO";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
