// @ts-expect-error Vite virtual module generated by @ilha/router
import { pageRouter, registry } from "ilha:pages/server";
import { hostname, shiki } from "imprensa/config";
import {
  getMdxHead,
  headDefaults,
  mdxRoutes,
  renderMdx,
  setPrerenderedMdxHtml,
} from "imprensa/mdx";
import { createPrerender } from "imprensa/prerender";

/** SSG-only entry — must not call `init()` (see `main.ts` for the browser). */
export const prerender = createPrerender({
  pageRouter,
  registry,
  mdxRoutes,
  renderMdx,
  setPrerenderedMdxHtml,
  getMdxHead,
  headDefaults,
  hostname: hostname || undefined,
  shiki,
});
