import { Outer, type InferRouter } from "@outerjs/server";
import { fromRecord } from "@outerjs/server/secrets";
import { type OuterStorage } from "@outerjs/server/storage";
import { emailOTP } from "better-auth/plugins";
import { DurableObject } from "cloudflare:workers";
import { DurableObjectSqliteDialect } from "kysely-durable-objects";
import { z } from "zod";

import { v1_0_0 } from "./schema";

/**
 * `OuterStorage` is three methods on purpose, so a backend needs no adapter package —
 * an R2 binding maps onto it directly. (`fromS3` covers the `@aws-sdk/client-s3`
 * command shape instead; R2's native binding is simpler than that.)
 */
function fromR2(bucket: R2Bucket): OuterStorage {
  return {
    async get(key) {
      const object = await bucket.get(key);
      return object ? new Uint8Array(await object.arrayBuffer()) : null;
    },
    async set(key, bytes) {
      await bucket.put(key, bytes);
    },
    delete: (key) => bucket.delete(key),
  };
}

// one DO instance (see idFromName below) = one SQLite DB, like PGlite's local file
export class OuterDO extends DurableObject<Env> {
  readonly outer;
  private readonly ready: Promise<unknown>;

  constructor(ctx: DurableObjectState, _env: Env) {
    super(ctx, _env);

    // Cloudflare's `Env` (generated by `wrangler types`) already types the bindings and
    // secrets, so there's no schema to re-declare — `fromRecord` takes the typed env straight
    // and infers `OuterSecrets<Env>`. Pass `secrets` to `new Outer({ secrets })` too, so
    // procedures read the same values via `context.secrets`.
    //
    // BASE_URL / COOKIE_PREFIX / CORS_ORIGINS come from `.dev.vars` / wrangler and aren't in
    // the generated `Env`; declare them here and default each at the use site below.
    const secrets = fromRecord(
      _env as Env & { BASE_URL?: string; COOKIE_PREFIX?: string; CORS_ORIGINS?: string },
    );

    this.outer = new Outer({
      name: "Outer",
      baseUrl: secrets.get("BASE_URL") ?? "http://localhost:8787",
      db: {
        dialect: new DurableObjectSqliteDialect(ctx.storage.sql as any),
        kind: "sqlite",
      },
      // comma-separated origins (e.g. an admin dashboard); the default is the hosted hub
      cors: {
        origins: (secrets.get("CORS_ORIGINS") ?? "https://hub.outer.now")
          .split(",")
          .map((o) => o.trim())
          .filter(Boolean),
        credentials: true,
      },
      // Uploaded bytes go to R2, not the DO — see the OUTER_FILES binding in wrangler.jsonc
      storage: fromR2(secrets.get("OUTER_FILES")),
      // Surfaced as `context.secrets` — read the same env values in any procedure
      secrets,
    })
      .schema(v1_0_0)
      .auth({
        secret: secrets.get("AUTH_SECRET") ?? "dev-only-secret",
        // namespaces this instance's auth cookies — set a unique value per instance so several
        // Outer instances on the same host (localhost ports share one cookie jar) stay separate
        advanced: { cookiePrefix: secrets.get("COOKIE_PREFIX") ?? "outer-cloudflare" },
        emailAndPassword: { enabled: true },
        user: {
          // `input: false` blocks signups from setting their own role — only the seed (or an admin) can
          additionalFields: { role: { type: "string", defaultValue: "user", input: false } },
        },
        plugins: [
          emailOTP({
            // OTP is sign-in only: it can't create accounts, so the seeded admin stays the only admin
            disableSignUp: true,
            async sendVerificationOTP({ email, otp }) {
              console.log(">>>OTP", { email, otp });
            },
          }),
        ],
      })
      .openapi()
      .admin()
      // Adds file.upload / list / get / delete / attach / detach plus GET /files/:id.
      // Files default to private: only the uploader can read or delete them.
      .files({ maxBytes: 10 * 1024 * 1024 })
      .resource("post")
      .procedure("post.count", (base) =>
        base.output(z.object({ count: z.number() })).handler(async ({ context }) => {
          const rows = await context.db
            .selectFrom("post")
            .select(context.db.fn.countAll().as("count"))
            .execute();
          return { count: Number(rows[0]?.count ?? 0) };
        }),
      )
      .build();

    this.ready = ctx.blockConcurrencyWhile(async () => {
      const { error } = await this.outer.migrator.migrateToLatest();
      if (error) return console.error(error);

      // Seed the single admin account: no password, so email OTP is its only sign-in path.
      // Idempotent — re-running promotes an existing user with this email instead of duplicating.
      // Values are SQLite-shaped (ISO strings, 1/0): the DO driver passes params straight to
      // `sql.exec`, which rejects `Date` and boolean bindings.
      const adminEmail = secrets.get("ADMIN_EMAIL");
      if (adminEmail) {
        const now = new Date().toISOString();
        await this.outer.db
          .insertInto("user")
          .values({
            id: crypto.randomUUID(),
            name: "Admin",
            email: adminEmail,
            emailVerified: 1,
            role: "admin",
            banned: 0,
            createdAt: now,
            updatedAt: now,
          } as never)
          .onConflict((oc) => oc.column("email").doUpdateSet({ role: "admin" } as never))
          .execute();
        console.info("[Outer] Admin account seeded");
      }
    });
  }

  override async fetch(request: Request): Promise<Response> {
    await this.ready;
    return this.outer.handle(request);
  }
}

export type Router = InferRouter<OuterDO["outer"]>;

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    // swap for idFromName(orgId) etc for per-tenant DBs
    const id = env.OUTER_DO.idFromName("singleton");
    const stub = env.OUTER_DO.get(id);
    return stub.fetch(request);
  },
} satisfies ExportedHandler<Env>;
