name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - run: bun install

      - run: bun run test

      - run: bun run build

      - run: bunx pkg-pr-new publish ./packages/server ./packages/sdk
